[package]
name = "mayaqua-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Core utilities for Mayaqua library (Memory, Buffers, Strings)"

[dependencies]
libc.workspace = true

[lib]
name = "mayaqua_core"
crate-type = ["rlib"]
