name: SoftEtherClient CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-macos:
    name: Build SoftEtherClient (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.0

      - name: Show Zig version
        run: zig version

      - name: Install dependencies (macOS)
        run: |
          brew install openssl@3

      - name: Build TapTun library
        run: |
          cd TapTun
          zig build -Doptimize=ReleaseFast
          ls -lh zig-out/lib/

      - name: Build SoftEtherClient
        run: |
          zig build -Doptimize=ReleaseFast
          ls -lh zig-out/lib/

      - name: Run tests
        run: |
          zig build test

