name: SoftEtherClient CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-macos:
    name: Build SoftEtherClient (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Show Zig version
        run: zig version

      - name: Install dependencies (macOS)
        run: |
          brew install openssl@3

      - name: Build TapTun library
        run: |
          cd TapTun
          zig build -Doptimize=ReleaseFast
          ls -lh zig-out/lib/

      - name: Build SoftEtherClient
        run: |
          zig build -Doptimize=ReleaseFast
          ls -lh zig-out/lib/

      - name: Run tests
        run: |
          zig build test

  build-ios:
    name: Build SoftEtherClient (iOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show versions
        run: |
          zig version
          xcodebuild -version
          xcode-select -p

      - name: Install dependencies
        run: |
          brew install openssl@3

      - name: Build TapTun for iOS (arm64)
        run: |
          cd TapTun
          zig build ios-device -Doptimize=ReleaseFast
          ls -lh zig-out/lib/aarch64-ios/

      - name: Build iOS Framework with Xcode
        run: |
          ./scripts/build_with_xcode.sh

      - name: Verify XCFramework
        run: |
          ls -lh ../ZigFramework/SoftEtherClient.xcframework/
          file ../ZigFramework/SoftEtherClient.xcframework/ios-arm64/libSoftEtherClient.a
